### ISSUE TITLE
CMAKE_INSTALL_PREFIX is NOT functioning...

### ISSUE THREAD

**Issue by jiapei100** [giladreich/ImGui-CMake-Installer#2]
Looks like: there is nowhere to set up **CMAKE_INSTALL_PREFIX**..

**Comment by giladreich** [comment]
> Looks like: there is nowhere to set up **CMAKE_INSTALL_PREFIX**..

Hi @jiapei100, this is because it gets overridden in the script. I wrote this almost 5 years ago, so I'll adjust the code a bit.
